version: '3.2'

services:

  stt-worker:
    container_name: linto-stt-worker
    image: lintoai/linto-platform-stt-worker-client
    depends_on:
      - stt-server
    volumes:
      - ${AM_PATH}:/opt/models/AM
      - ${LM_PATH}:/opt/models/LM
      - ${MODEL_CONFIG}:/opt/worker.config
    env_file: .dockerenv
    environment:
      - OFFLINE_PORT
    networks:
      - internal

  stt-server:
    container_name: linto-stt-server
    image: lintoai/linto-platform-stt-server
    hostname: stt-server
    env_file: .dockerenv
    environment:
      - OFFLINE_PORT
    networks:
      - internal
      - linto_net

  swaggerui:
    container_name: linto-stt-swagger
    image: swaggerapi/swagger-ui
    hostname: swaggerui
    volumes:
      - ${SWAGGER_PATH}:/app/swagger/
    env_file: .dockerenv
    environment:
      - SWAGGER_JSON
    networks:
      - linto_net


networks:
    internal:
    linto_net:
       external: true

