version: '3.5'

services:

  stt-worker:
    container_name: linto-stt-worker
    image: lintoai/linto-platform-stt-worker-client
    depends_on:
      - stt-server
    env_file: .docker_env
    volumes:
      - ${AM_PATH}:/opt/models/AM
      - ${LM_PATH}:/opt/models/LM
      - ./worker.config:/opt/worker.config
    networks:
      - internal

  stt-server:
    container_name: linto-stt-server
    image: lintoai/linto-platform-stt-server
    hostname: stt-server
    env_file: .docker_env
    networks:
      - internal
      - linto_net

  swaggerui:
    container_name: linto-stt-swagger
    image: swaggerapi/swagger-ui
    hostname: swaggerui
    env_file: .docker_env
    volumes:
      - ./document:/app/swagger/
    networks:
      - linto_net


networks:
    internal:
    linto_net:
       external: true

