version: '3.5'

services:
  linto-bls:
    container_name: linto-business-logic-server
    image: lintoai/linto-platform-business-logic-server
    env_file: ${PWD}/business-logic-server/.docker_env
    networks:
      - linto_net

networks:
    linto_net:
       external: true
