version: '3'

services:

  mongo:
    image: mongo:3.6.5
    volumes:
      - tockmongo:/data/db
    ports:
      - "127.0.0.1:27017:27017"
    command: --smallfiles --bind_ip_all --port 27017 --replSet "tock"
    networks:
      - internal
      
  mongo2:
    image: mongo:3.6.5
    depends_on:
      - mongo
    volumes:
      - tockmongo2:/data/db
    ports:
      - "127.0.0.1:27018:27018"
    command: --smallfiles --bind_ip_all --port 27018 --replSet "tock"
    networks:
      - internal

  mongo3:
    image: mongo:3.6.5
    depends_on:
      - mongo
      - mongo2
    volumes:
      - tockmongo3:/data/db
    ports:
      - "127.0.0.1:27019:27019"
    command: --smallfiles --bind_ip_all --port 27019 --replSet "tock"
    networks:
      - internal

  mongo-setup:
    container_name: "mongo-setup"
    image: mongo:3.6.5
    depends_on:
      - "mongo"
      - "mongo2"
      - "mongo3"
    links:
      - mongo:mongo
      - mongo2:mongo2
      - mongo3:mongo3
    volumes:
      - ./scripts:/scripts
    environment:
      - MONGO1=mongo
      - MONGO2=mongo2
      - MONGO3=mongo3
      - RS=tock
    entrypoint: [ "/scripts/setup.sh" ]
    networks:
      - internal

  build_worker:
    image: tock/build_worker:$TAG
    depends_on:
      - mongo
      - mongo2
      - mongo3
    environment:
      - tock_mongo_url=mongodb://mongo:27017,mongo2:27018,mongo3:27019/?replicaSet=tock
      - tock_env=prod
      - JAVA_ARGS=-Xmx1g -XX:MaxMetaspaceSize=256m
    networks:
      - internal

  duckling:
    image: tock/duckling:$TAG
    environment:
      - tock_env=prod
    expose:
      - "8080"
    networks:
      - internal

  kotlin_compiler:
    image: tock/kotlin_compiler:$TAG
    environment:
      - tock_env=prod
      - tock_kotlin_compiler_classpath=/maven
    networks:
      - internal

  admin_web:
    image: tock/bot_admin:$TAG
    depends_on:
      - mongo
      - mongo2
      - mongo3
      - duckling
      - kotlin_compiler
    environment:
      - tock_mongo_url=mongodb://mongo:27017,mongo2:27018,mongo3:27019/?replicaSet=tock
      - nlp_duckling_url=http://duckling:8080
      - tock_env=prod
      - tock_bot_admin_rest_default_base_url=http://bot_open_data:8080
      - tock_bot_compiler_service_url=http://kotlin_compiler:8080
      #remove this in production
      - tock_https_env=false
      - botadminverticle_body_limit=-1
    ports:
      - "127.0.0.1:81:8080"
    networks:
      - internal
      - linto_net

  nlp_api:
    image: tock/nlp_api:$TAG
    depends_on:
      - mongo
      - mongo2
      - mongo3
      - duckling
    environment:
      - tock_mongo_url=mongodb://mongo:27017,mongo2:27018,mongo3:27019/?replicaSet=tock
      - nlp_duckling_url=http://duckling:8080
      - tock_env=prod
      - tock_web_use_default_cors_handler=true
      - tock_web_use_default_cors_handler_with_credentials=false
      - tock_web_use_default_cors_handler_url=*
    ports:
      - "127.0.0.1:8888:8080"
    networks:
      - internal
      - linto_net

volumes:
  tockmongo:
  tockmongo2:
  tockmongo3:

networks:
  internal:
  linto_net:
    external: true