version: '3.5'

services:

  nginx:
    container_name: nginx
    image: nginx
    depends_on:
      - linto-admin
      - linto-bls
      - linto-mqtt
      - stt-server-en
      - stt-server-fr
      - linto-nlu-web
      - linto-nlp-api
    volumes:
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
    networks:
      - linto_net

networks:
    linto_net:
       external: true
