version: '3.5'

services:
  linto-overwatch:
    container_name: linto-platform-overwatch
    image: lintoai/linto-platform-overwatch
    env_file: ${PWD}/overwatch/.docker_env
    depends_on:
      - nginx
    networks:
      - linto_net

networks:
  linto_net:
    external: true
