version: '3.5'

services:
  overwatch:
    container_name: linto-overwatch
    image: lintoai/linto-platform-overwatch
    env_file: ${PWD}/overwatch/.docker_env
    networks:
      - internal

networks:
  internal:
