version: '3.5'

services:

  stt-worker_standelone:
    container_name: linto-stt-worker-standalone
    image: lintoai/linto-platform-stt-standalone-worker
    volumes:
      - ${AM_PATH_STANDALONE}:/opt/models/AM
      - ${LM_PATH_STANDALONE}:/opt/models/LM
    env_file: ${PWD}/stt-standalone-worker/.docker_env
    networks:
      - linto_net

networks:
    linto_net:
       external: true

