version: '3.5'

services:
  linto-admin:
    container_name: linto-platform-admin
    image: lintoai/linto-platform-admin
    depends_on:
      - mongo-admin
      - redis-admin
    env_file: ${PWD}/admin/.docker_env
    networks:
      - linto_net
      - internal
  mongo-admin:
    container_name: linto-admin-mongo
    image: mongo:latest
    restart: always
    volumes:
      - ${HOME}/.linto-admin-dbdata:/data/db
      - ${PWD}/admin/mongodb/seed:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: lintoAdmin
    networks:
     - linto_net
     - internal
  redis-admin:
    container_name: linto-admin-redis
    image: redis:latest
    networks:
      - internal

networks:
  linto_net:
    external: true
  internal:
