version: '3.5'

services:
  linto-admin:
    container_name: linto-admin
    image: lintoai/linto-platform-admin
    depends_on:
      - mongo
      - redis
    env_file: .docker_env
    networks:
     - internal
     - linto_net
  mongo-admin:
    container_name: linto-admin-mongo
    image: mongo:latest
    restart: always
    volumes:
      - ${HOME}/linto-admin-dbdata:/data/db
      - ./mongodb/seed:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: lintoAdmin
    networks:
     - internal
  redis:
    container_name: linto-admin-redis
    image: redis:latest
    networks:
      - internal

networks:
  internal:
  linto_net:
    external: true
